http-server:
  # require: web server bind ip
  ip: 0.0.0.0
  # require: web server bind port
  port: 8848
  # public-host: public network host, resolve the inconsistency between the host bound in the proxy and container, provide a public network accessible interface
  # default: http://${ip}:${host}
  # public-host will affect the generation of upload interfaces for image capture
  public-host: http://192.168.1.11:8848

datasource:
  # require: currently, only MySQL and PostgreSQL are supported
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: CrestedIbis
  db-name: CrestedIbis
  max-idle: 10
  max-open: 10

store:
  # GB28181 snapshot upload image storage location
  snapshot: store/snapshot

jwt:
  key: CrestedIbis
  expire-time: 3600

log:
  file: CrestedIbis.log
  # support: Trace Debug Info Waring Error Fatal Panic
  level: Info

# GB28181 config
gb28181:
  serial: 34020000001320000001
  realm: 3402000000
  password: admin123
  # default: true
  # if true: an INVITE sip request will be automatically initiated during Keepalive when the stream has been disconnected
  auto-invite: true
  # support: Trace Debug Info Waring Error Fatal Panic
  log-level: Info
  sip-server:
    # default: 0.0.0.0
    ip: 192.168.1.11
    # default: 5060
    port: 5060
    mode: udp
  media-server:
    secret: Uva5PKPA1aGOoBiQHglYExH2kMi2cX2S
    ip: 192.168.10.49
    port: 80
    mode: tcp
  http-server:
    port: 18080