services:
  CrestedIbis-DB:
    image: mysql:8.0.40
    hostname: CrestedIbis-DB
    container_name: CrestedIbis-DB
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: CrestedIbis
      MYSQL_DATABASE: CrestedIbis
    

  CrestedIbis-Media:
    # 2024-10-19T13:20:31: 4c90a1a
    image: zlmediakit/zlmediakit:master
    hostname: CrestedIbis-Media
    container_name: CrestedIbis-Media
    ports:
      # ZLM
      # ZLM-HTTP
      - "8080:80"
      # ZLM-RTP
      - "10000:10000/tcp"
      - "10000:10000/udp"
      # ZLM-RTP_PROXY
      - "30000-30500:30000-30500/tcp"
      - "30000-30500:30000-30500/udp"
    volumes:
      - ./CrestedIbis-Media.ini:/opt/media/conf/config.ini:ro
    environment:
      TZ: Asia/Shanghai