// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "北溪入江流(focus1024)",
            "url": "http://focus1024.com(https://github.com/focus1024-wind/CrestedIbis)",
            "email": "focus1024@foxmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ipc/device": {
            "get": {
                "description": "根据device_id获取IPC设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPC设备 /ipc/device"
                ],
                "summary": "根据device_id获取IPC设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "access_token",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ipc_device.IpcDevice"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "查询数据失败",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "更新IPC设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPC设备 /ipc/device"
                ],
                "summary": "更新IPC设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "access_token",
                        "in": "query"
                    },
                    {
                        "description": "设备信息",
                        "name": "IpcDevice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ipc_device.IpcDevice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ipc_device.IpcDevice"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "查询数据失败",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除IPC设备及对应通道，该删除仅为删除数据库记录，不影响IPC设备的重新注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPC设备 /ipc/device"
                ],
                "summary": "删除IPC设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "access_token",
                        "in": "query"
                    },
                    {
                        "description": "设备ID",
                        "name": "IpcDeviceID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ipc_device.IpcDeviceID"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询数据成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "查询数据失败",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ipc/device/alarms": {
            "get": {
                "description": "分页查询IpcDevice设备报警信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPC设备 /ipc/device"
                ],
                "summary": "分页查询IpcDevice设备报警信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "access_token",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页查询页码，默认值: 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页查询数量，默认值: 15",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "通道ID",
                        "name": "channel_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间，默认值: 2006-01-02 15:04:05",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束时间，默认值: 当前时间",
                        "name": "end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分页查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ipc_alarm.IpcAlarmPage"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "查询数据失败",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ipc/device/channel": {
            "post": {
                "description": "更新IPC通道",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPC设备 /ipc/device"
                ],
                "summary": "更新IPC通道",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "access_token",
                        "in": "query"
                    },
                    {
                        "description": "设备信息",
                        "name": "IpcDevice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ipc_device.IpcDevice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ipc_device.IpcChannel"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "查询数据失败",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ipc/device/channels": {
            "get": {
                "description": "查询GB28181 设备对应通道信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPC设备 /ipc/device"
                ],
                "summary": "获取设备通道信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "access_token",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询数据成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/ipc_device.IpcChannel"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "查询数据失败",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ipc/device/devices": {
            "get": {
                "description": "分页查询GB28181 IpcDevice设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPC设备 /ipc/device"
                ],
                "summary": "分页查询IpcDevice设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "access_token",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页查询页码，默认值: 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页查询数量，默认值: 15",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分页查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ipc_device.IpcDevicePage"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "查询数据失败",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ipc/device/records": {
            "get": {
                "description": "分页查询IpcDevice设备录像信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPC设备 /ipc/device"
                ],
                "summary": "分页查询IpcDevice设备录像信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "access_token",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页查询页码，默认值: 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页查询数量，默认值: 15",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "通道ID",
                        "name": "channel_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间，默认值: 2006-01-02 15:04:05",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束时间，默认值: 当前时间",
                        "name": "end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分页查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ipc_alarm.IpcRecordPage"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "查询数据失败",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ipc/device/upload_image": {
            "post": {
                "description": "GB28181图像抓拍，图片上传接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPC设备 /ipc/device"
                ],
                "summary": "IPC图像上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "access_token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "上传图片",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传图片成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "上传图片失败",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ipc/media/play": {
            "post": {
                "description": "Ipc设备点播",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设备点播 /ipc/media"
                ],
                "summary": "Ipc设备点播",
                "parameters": [
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "访问token",
                        "name": "access_token",
                        "in": "query"
                    },
                    {
                        "description": "点播参数",
                        "name": "IpcMediaPlayModel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ipc_media.IpcMediaPlayModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功，响应点播地址",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "注册失败，响应失败信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/system/user/login": {
            "post": {
                "description": "用户登录并生成用户登录日志信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理 /system/user"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录信息，密码采用加盐加密",
                        "name": "SysLoginUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.SysUserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，响应JWT",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "登录失败，响应失败信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/system/user/register": {
            "post": {
                "description": "注册用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理 /system/user"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "description": "用户注册信息，密码采用加盐加密",
                        "name": "SysUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.SysUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/model.HttpResponse"
                        }
                    },
                    "500": {
                        "description": "注册失败，响应失败信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ipc_alarm.IpcAlarm": {
            "type": "object",
            "properties": {
                "alarm_description": {
                    "type": "string"
                },
                "alarm_method": {
                    "type": "string"
                },
                "alarm_priority": {
                    "type": "string"
                },
                "alarm_time": {
                    "type": "string"
                },
                "alarm_type": {
                    "type": "string"
                },
                "channel_id": {
                    "type": "string"
                },
                "created_time": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ipc_records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ipc_alarm.IpcRecord"
                    }
                },
                "latitude": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "updated_time": {
                    "type": "string"
                }
            }
        },
        "ipc_alarm.IpcAlarmPage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ipc_alarm.IpcAlarm"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "ipc_alarm.IpcRecord": {
            "type": "object",
            "properties": {
                "alarmID": {
                    "type": "integer"
                },
                "app": {
                    "type": "string"
                },
                "created_time": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "stream": {
                    "type": "string"
                },
                "time_len": {
                    "type": "number"
                },
                "updated_time": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "ipc_alarm.IpcRecordPage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ipc_alarm.IpcRecord"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "ipc_device.IpcChannel": {
            "type": "object",
            "properties": {
                "created_time": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "state": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_time": {
                    "type": "string"
                }
            }
        },
        "ipc_device.IpcDevice": {
            "type": "object",
            "properties": {
                "channel_num": {
                    "type": "integer"
                },
                "created_time": {
                    "type": "string"
                },
                "device_addr": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "from_address": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ipc_channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ipc_device.IpcChannel"
                    }
                },
                "keepalive_time": {
                    "type": "string"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "register_time": {
                    "type": "string"
                },
                "sn": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_time": {
                    "type": "string"
                }
            }
        },
        "ipc_device.IpcDeviceID": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string"
                }
            }
        },
        "ipc_device.IpcDevicePage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ipc_device.IpcDevice"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "ipc_media.IpcMediaPlayModel": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "end": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "model.HttpResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "user.RoleGroup": {
            "type": "object",
            "properties": {
                "created_time": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                },
                "role_name": {
                    "type": "string"
                },
                "updated_time": {
                    "type": "string"
                },
                "user": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.SysUser"
                    }
                }
            }
        },
        "user.SysUser": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_time": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "example": "CrestedIbis"
                },
                "phone": {
                    "type": "string"
                },
                "roleGroups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.RoleGroup"
                    }
                },
                "sex": {
                    "type": "integer"
                },
                "updated_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "user.SysUserLogin": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "CrestedIbis"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "CrestedIbis",
	Description:      "CrestedIbis目前是一个基于GB28181标准实现的音视频云平台，负责实现GB28181信令和设备管理，未来将会是一个支持物联网设备接入，算法训练和部署的综合物联网平台。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
