definitions:
  ipc_device.IpcChannel:
    properties:
      created_time:
        type: string
      device_id:
        type: string
      id:
        type: integer
      manufacturer:
        type: string
      model:
        type: string
      name:
        type: string
      parent_id:
        type: string
      state:
        type: integer
      status:
        type: string
      updated_time:
        type: string
    type: object
  ipc_device.IpcDevice:
    properties:
      created_time:
        type: string
      device_addr:
        type: string
      device_id:
        type: string
      from_address:
        type: string
      id:
        type: integer
      ipcChannels:
        items:
          $ref: '#/definitions/ipc_device.IpcChannel'
        type: array
      manufacturer:
        type: string
      model:
        type: string
      name:
        type: string
      register_time:
        type: string
      sn:
        type: integer
      status:
        type: string
      updated_time:
        type: string
    type: object
  ipc_device.IpcDevicePage:
    properties:
      data:
        items:
          $ref: '#/definitions/ipc_device.IpcDevice'
        type: array
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
    type: object
  model.HttpResponse:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  user.RoleGroup:
    properties:
      created_time:
        type: string
      role_id:
        type: integer
      role_name:
        type: string
      updated_time:
        type: string
      user:
        items:
          $ref: '#/definitions/user.SysUser'
        type: array
    type: object
  user.SysUser:
    properties:
      avatar:
        type: string
      created_time:
        type: string
      email:
        type: string
      nickname:
        type: string
      password:
        example: CrestedIbis
        type: string
      phone:
        type: string
      roleGroups:
        items:
          $ref: '#/definitions/user.RoleGroup'
        type: array
      sex:
        type: integer
      updated_time:
        type: string
      user_id:
        type: integer
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  user.SysUserLogin:
    properties:
      password:
        example: CrestedIbis
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
info:
  contact:
    email: focus1024@foxmail.com
    name: 北溪入江流(focus1024)
    url: http://focus1024.com(https://github.com/focus1024-wind/CrestedIbis)
  description: CrestedIbis目前是一个基于GB28181标准实现的音视频云平台，负责实现GB28181信令和设备管理，未来将会是一个支持物联网设备接入，算法训练和部署的综合物联网平台。
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: CrestedIbis
  version: 0.0.1
paths:
  /ipc/device/channels:
    get:
      consumes:
      - application/json
      description: 查询GB28181 设备对应通道信息
      parameters:
      - description: 访问token
        in: header
        name: Authorization
        type: string
      - description: 访问token
        in: query
        name: access_token
        type: string
      - description: 设备ID
        in: query
        name: device_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 查询数据失败
          schema:
            allOf:
            - $ref: '#/definitions/model.HttpResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: 获取设备通道信息
      tags:
      - IPC设备 /ipc/device
  /ipc/device/devices:
    get:
      consumes:
      - application/json
      description: 分页查询GB28181 IpcDevice设备
      parameters:
      - description: 访问token
        in: header
        name: Authorization
        type: string
      - description: 访问token
        in: query
        name: access_token
        type: string
      - description: '分页查询页码，默认值: 1'
        in: query
        name: page
        type: integer
      - description: '每页查询数量，默认值: 15'
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询数据失败
          schema:
            allOf:
            - $ref: '#/definitions/model.HttpResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: 分页查询IpcDevice设备
      tags:
      - IPC设备 /ipc/device
  /ipc/device/upload_image:
    post:
      consumes:
      - multipart/form-data
      description: GB28181图像抓拍，图片上传接口
      parameters:
      - description: 访问token
        in: query
        name: access_token
        required: true
        type: string
      - description: 上传图片
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 上传图片失败
          schema:
            allOf:
            - $ref: '#/definitions/model.HttpResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: IPC图像上传
      tags:
      - IPC设备 /ipc/device
  /system/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录并生成用户登录日志信息
      parameters:
      - description: 用户登录信息，密码采用加盐加密
        in: body
        name: SysLoginUser
        required: true
        schema:
          $ref: '#/definitions/user.SysUserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功，响应JWT
          schema:
            allOf:
            - $ref: '#/definitions/model.HttpResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: 登录失败，响应失败信息
          schema:
            allOf:
            - $ref: '#/definitions/model.HttpResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: 用户登录
      tags:
      - 用户管理 /system/user
  /system/user/register:
    post:
      consumes:
      - application/json
      description: 注册用户
      parameters:
      - description: 用户注册信息，密码采用加盐加密
        in: body
        name: SysUser
        required: true
        schema:
          $ref: '#/definitions/user.SysUser'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/model.HttpResponse'
        "500":
          description: 注册失败，响应失败信息
          schema:
            allOf:
            - $ref: '#/definitions/model.HttpResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: 注册用户
      tags:
      - 用户管理 /system/user
swagger: "2.0"
